### PR TITLE
docs: comprehensive documentation updates

### PR DESCRIPTION
**Pull request by cuebit**
This PR brings the documentation further clarity on setup and usage.

#### Type of PR:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Documentation
- [ ] Other, please describe:

#### Breaking changes:

- [x] No
- [ ] Yes

### Details

The documentation for Vuex ORM Axios has received some much needed refinement. They have been primarily revised to:

- [x] bring clarity on plugin usage
- [x] bring clarity on configuration options
- [x] align installation & setup with recent plugins
- [x] updated sponsors

### CODE REVIEW

**Comment by cuebit** [comment]
@kiaking

There a couple of outstanding items to revise (see checklist), would be keen to get your input and if you might have anything to add?

**Comment by kiaking** [comment]
@cuebit Thank you so much for this! Looking pretty good to me though. I guess this plugin also needs some tweaks from Vuex ORM 1.0.0-draft release. Maybe we should be updating all core plugins at the same time as well.

**Comment by cuebit** [comment]
@kiaking agreed. I think principle behaviour of this plugin will remain the same, while the underlying functionality will change and be aligned to core 1.0.0.

The documentation would remain unchanged to some extent, so we can still distribute these documentation changes, and perhaps come back and tweak should the impact of core impact the concept of this plugin.

What do you think?

**Comment by kiaking** [comment]
@cuebit Yea that's perfectly valid. We should release this docs either way 👍

**Comment by cuebit** [comment]
@kiaking can you give this a final glaze, and if happy, I'll merge and deploy docs. 👍

**Comment by kiaking** [comment]
Thanks a lot! This looks perfect 🙌  Pleale go ahead and deploy this one 👍

**Pull request merged**
