### PR TITLE
Merge configs using lodash merge

### LINKED ISSUE #97: Merge configs
Currently object unpacking is being used to combine all of the configs. This does not allow setting axios settings higher up in the config stack that are objects.
For example, if I want a global param for all requests I would expect to be able to go:
```javascript
VuexORM.use(VuexORMAxios, {
	params: {
		key: "foo"
	}
});
```
Currently any lower config specifying params will overwrite this.
Something along the lines of lodash merge should be used.
If I wanted to unset a setting higher up I can simply do something like:
```javascript
Model.get('url', {
	params: {
		key: undefined
	}
});
```

### PR DESCRIPTION
**Pull request by innovate-invent**
Fixes #97

### CODE REVIEW

**Comment by kiaking** [comment]
Thank you so much for the PR! Sorry but could we not use lodash? It adds to the bundle size quite a bit...

**Comment by innovate-invent** [comment]
It imports the lodash submodule for that function only, is that still large?

**Comment by kiaking** [comment]
Unfortunately yes... we had same problem at Vuex ORM Core. Lodash uses many common functions, so even if you import only specific features, it still loads unnecessary codes.

I really hate this too, but it's how JS libraries have to do things I guess...

**Comment by innovate-invent** [comment]
I guess the code will have to be ripped out of the lodash library..

**Comment by kiaking** [comment]
Yeah that's what I did when implementing `orderBy` feature at Vuex ORM Core. You could check this one out though.
https://github.com/vuex-orm/vuex-orm/blob/3c642728b829006a93ac1d1f9b33144d109ad606/src/support/Utils.ts#L214

**Comment by cuebit** [comment]
Yea, lodash is a simple fix but adds considerable weight and a significant performance impact.

The clone example that @kiaking is referring to may point you in the right direction – it's quite verbose because performance is crucial for Vuex ORM – so it could easily be half the code. 

Note, the signature for type-safe merging is considerably more complex than cloning. If you wish to preserve types. Sometimes I abhor TS.

**Comment by cuebit** [comment]
Closing due to inactivity. I don't believe there's been much steer on this topic to warrant this PR progressing.

**Pull request closed without merging**
