### PR TITLE
Clear all data on model , if API return as empty

### PR DESCRIPTION
**Pull request by mean-cj**
Fix clear data on the model ,
if API response from response is return as empty data.

### CODE REVIEW

**Comment by kiaking** [comment]
@mean-cj Thank you so much for the PR!

But I would like to discuss with this feature a bit more. I think maybe it's better to add an option to define which Vuex ORM method should be used on persistent. Because if you pass an empty array to Vuex ORM `insert` method, it will do nothing (current behavior). And sometimes it's desired too. 

So how about adding these options

`persistBy`
`insert`
`create`
`insertOrUpdate`
`update`
`delete`

`persistBy` method defines what method should be used as a default.

```js
User.api().get('/users', {
  persistBy: 'create' // Default is `insertOrUpdate`
})

// Is equal to.
User.create({ data })
```

Other options work as same as Vuex ORM persistent methods.

```js
User.api().get('/users', {
  insert: ['posts']
})

// Is equal to.
User.create({ data, insert: ['posts'] })
```

**Comment by mean-cj** [comment]
Hello @kiaking 
Thank you so much for your answer.

I think clear all data on the model is better than define persistBy
because it make sense , if ajax response data is empty.

Example 1 : When i delete final id
Item.api().delete('/delete/item/${id}') 
the last response data is empty, clear data on the model

Example 2: if other device have been fetch data
if ajax response data is empty clear all data on the model

---------------------------------------

today i will found after fetch data from api()
the data on model not sync or not auto delete data id 
if the id is not exists on API response

**API Response : Item.fetch()**
[  {id:1 , name:'aaaaa'}, {id:3 , name:'cccc'} ] ]

**Example My PC**
Current Item Model have been data
[  {id:1 , name:'aaaaa'}, {id:2 , name:'bbbb'} ] ]

**Call Item.all() have response**
[  {id:1 , name:'aaaaa'}, {id:2 , name:'bbbb'} , {id:3 , name:'cccc'} ] ]
item id=2 is not delete

i think create "sync" variable for enable sync mode
use for model sync all data from api response

User.api().fetch('/users', {
  sync: true
})

if (config.sync || !data || data.length === 0) {
   this.model.deleteAll()
}

**Comment by mean-cj** [comment]
idea override option work only return all data.

add refresh method is better , use for sync between api with model
 **model.api().refresh()** 

```
  /**
   * Perform a refresh request.
   */
  refresh(url: string, config: Config = {}): Promise<Response> {
    this.model.deleteAll()
    return this.request({ method: 'get', url, ...config })
  }
```

**Comment by kiaking** [comment]
Yeah, I like the idea of having an `override` or a `sync` option. One thing to consider is what we do with relationships.

Let's say a user wants to fetch User. If the api response only contains users records, it would be safe to delete all users when the `override` option is set to true.

But if the user response could contain relationships, for example, posts records as well, it would be hard to find out what post record should be deleted.

I don't think there is an easy way to handle this situation. Therefore, I think it would be a bit more intuitive to have options for users to choose what Vuex ORM persistent method to use (`create`, `insert`, etc.). Because the override option is essentially the same as the `create` method on Vuex ORM Core.

What do you think?

**Comment by mean-cj** [comment]
Hello @kiaking 
I agree with you , i found problem with relation 
How can i do make the sync() function on model

Example
this.sync().hasMany(Comment, 'post_id')
this.sync().get()
this.sync().post()

when i will use the sync() 
call model.deleteAll() before sync from api response.

What do you think?

**Comment by mean-cj** [comment]
I add two function to @vuex-orm\core\src\model\Model.ts
```
  static sync(): any {
    this.dispatch('deleteAll')
    return this
  }

  $sync(): any {
    this.$dispatch('deleteAll')
    return this
  }
```

but doesn't work because when i call function on api() the model call sync() every time.
```
  static fields = () => {
    return {
      items: this.hasMany(PosItem.sync(), 'order_id')
    }
  }
```

**Comment by kiaking** [comment]
If we would like to delete all relationships and recreate everything with API response, we could simply iterate through fields and delete all records.

```ts
function persistResponseData (response: AxiosResponse, config: Config): Promise<any> {
  const fields = this.model.fields()

  Object.keys(fields).forEach((name) => {
    const related = this.model.relation(name)

    related && related.deleteAll()
  })

  return this.model.insertOrUpdate({
    data: this.getDataFromResponse(response, config)
  })
}
```

But there are all sorts of relationships between models, and models could relate to more than one model. If we delete everything, some other model might lose their relationship.

This is going to be very complicated when we think about more complex relationships like `belongsToMany` or `morphTo`. I really don't think it's a good idea to take this path...

 There(re too many edge cases. I think it should be handled by users if they really need this functionality.

**Comment by mean-cj** [comment]
Thank you so much

**Comment by kiaking** [comment]
I'll closing this PR for now. Maybe there'll be good idea to achieve something like this, though I think we should have discussion at issues.

**Pull request closed without merging**
