### PR TITLE
feat: adds configurable `persistBy` option

### LINKED ISSUE #93: delete all records then insert new one
if response is true then delete all data and insert new data otherwise ignore it.

### PR DESCRIPTION
**Pull request by cuebit**
Resolves #93

#### Type of PR:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Documentation
- [ ] Other, please describe:

#### Breaking changes:

- [x] No
- [ ] Yes

### Details

This PR adds a new optional `persistBy?: string` option to allow configuring a preferred method of persistence. The default value is `'insertOrUpdate'`.

In a nutshell, while [this issue comment](https://github.com/vuex-orm/plugin-axios/issues/93#issuecomment-613238938) explains the idea pretty well, the plugin option `persistBy` can be configured to override the default persistence behaviour. 

The signature for this options is: `'create' | 'insert' | 'update' | 'insertOrUpdate'`

Beyond that, the plugin will warn users of any invalid value configured and fallback to the default `insertOrUpdate` method.

> N.B. This PR intentionally publicises `getDataFromResponse` as discussed in a previous issue #112. I think it makes sense to allow users to still be able to retrieve data through configured requests when deferring persistence.

### CODE REVIEW

**Comment by cuebit** [comment]
Drafting this PR pending documentation.

@kiaking your input would be most appreciated.

**Comment by kiaking** [comment]
Thank you so much for this! I think it's looking good. Could we have `update` as an option as well...?

**Comment by cuebit** [comment]
Ah yea, if `update` is added to the union type, it seems to break the signature compatibility because the update methods signature is more broader than the others.

We could call the method explicitly:

```js
// invoker
this.entities = await this.persist(method, { data })

// invokee
persist(method: PersistOption, payload: any): Promise<Collections> {
  switch (method) {
    case 'create':
      return this.model.create(payload)
    case 'insert':
      return this.model.insert(payload)
    case 'update':
      return this.model.update(payload)
    case 'insertOrUpdate':
      return this.model.insertOrUpdate(payload)
  }
}
```

What do you think @kiaking?

**Comment by kiaking** [comment]
> We could call the method explicitly:

Yeah maybe that would be better, since `update` needs to be supported I think 👍

**Comment by cuebit** [comment]
The original idea of configuring the `save` option meant the `save()` method would only observe this option if persistence was not deferred.

For example, if a user chooses to defer persistence by setting `{ save: false }`, then later calling `save()` would withhold the ability to persist through a preferred persist method.

For that reason alone, reverting back to the original idea of configuring `persistBy` to a string value seemed like the most logical choice.

Users can now defer persistence and the `save()` will still respect the options set by the user:

```js
const response = User.api().get('...', { save: false, persistBy: 'create' })

// do something

response.save()
```

**Pull request merged**
